require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/splash_screens", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SplashScreen. As you add validations to SplashScreen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SplashScreen.create! valid_attributes
      get splash_screens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      splash_screen = SplashScreen.create! valid_attributes
      get splash_screen_url(splash_screen)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_splash_screen_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      splash_screen = SplashScreen.create! valid_attributes
      get edit_splash_screen_url(splash_screen)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SplashScreen" do
        expect {
          post splash_screens_url, params: { splash_screen: valid_attributes }
        }.to change(SplashScreen, :count).by(1)
      end

      it "redirects to the created splash_screen" do
        post splash_screens_url, params: { splash_screen: valid_attributes }
        expect(response).to redirect_to(splash_screen_url(SplashScreen.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SplashScreen" do
        expect {
          post splash_screens_url, params: { splash_screen: invalid_attributes }
        }.to change(SplashScreen, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post splash_screens_url, params: { splash_screen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested splash_screen" do
        splash_screen = SplashScreen.create! valid_attributes
        patch splash_screen_url(splash_screen), params: { splash_screen: new_attributes }
        splash_screen.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the splash_screen" do
        splash_screen = SplashScreen.create! valid_attributes
        patch splash_screen_url(splash_screen), params: { splash_screen: new_attributes }
        splash_screen.reload
        expect(response).to redirect_to(splash_screen_url(splash_screen))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        splash_screen = SplashScreen.create! valid_attributes
        patch splash_screen_url(splash_screen), params: { splash_screen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested splash_screen" do
      splash_screen = SplashScreen.create! valid_attributes
      expect {
        delete splash_screen_url(splash_screen)
      }.to change(SplashScreen, :count).by(-1)
    end

    it "redirects to the splash_screens list" do
      splash_screen = SplashScreen.create! valid_attributes
      delete splash_screen_url(splash_screen)
      expect(response).to redirect_to(splash_screens_url)
    end
  end
end
